FROM debian:bullseye
LABEL maintainer="michalis@mpi-sws.org"

WORKDIR /root

RUN export TERM='xterm-256color'

RUN apt-get update
RUN apt-get install -y -qq wget gnupg gnupg2 libtinfo5 bc \
    autoconf make automake libffi-dev zlib1g-dev libedit-dev \
    libxml2-dev xz-utils g++ clang

RUN apt-get install -y -qq \
    clang-6.0 libclang-6.0-dev llvm-6.0 llvm-6.0-dev \
    clang-8   libclang-8-dev   llvm-8   llvm-8-dev \
    clang-9   libclang-9-dev   llvm-9   llvm-9-dev \
    clang-10  libclang-10-dev  llvm-10  llvm-10-dev \
    clang-11  libclang-11-dev  llvm-11  llvm-11-dev

# COPY fetch_deps.sh ./fetch_deps.sh
# RUN ./fetch_deps.sh
