FROM debian:buster
LABEL maintainer="michalis@mpi-sws.org"

WORKDIR /root

RUN export TERM='xterm-256color'

RUN apt-get update
RUN apt-get install -y -qq wget gnupg gnupg2 libtinfo5 bc \
    autoconf make automake libffi-dev zlib1g-dev libedit-dev \
    libxml2-dev xz-utils g++ clang git

RUN apt-get install -y -qq \
    clang-6.0 libclang-6.0-dev llvm-6.0 llvm-6.0-dev \
    clang-7   libclang-7-dev   llvm-7   llvm-7-dev

# COPY fetch_deps.sh ./fetch_deps.sh
# RUN ./fetch_deps.sh
