#!/bin/bash

## out files
OUT_PREFIX="gitlab-ci-"
OUT_SUFFIX=".yml"

## headers
LINUX_HEADER="default:
  artifacts:
    expire_in: 1 week
    paths:
      - ./
"
MACOS_HEADER="default:
  tags:
    - macosx
  artifacts:
    expire_in: 1 week
    paths:
      - ./
"

## supported versions
LINUX_LLVM_VERSIONS="3.8 4.0 6.0 7 8 9"
MACOS_LLVM_VERSIONS="6.0 7 8 9"

declare -A LINUX_IMAGES
declare -A LINUX_IMAGES_VERSIONS

LINUX_IMAGES["imageA"]="localhost:5000/genmc-tool-stretch"
LINUX_IMAGES["imageB"]="localhost:5000/genmc-tool-bullseye"
LINUX_IMAGES_VERSIONS["imageA"]=" 3.8 4.0 7 " # spaces --> hack to match regex
LINUX_IMAGES_VERSIONS["imageB"]=" 6.0 8 9 "

find_image_name() {
    version=$1
    for i in "${!LINUX_IMAGES_VERSIONS[@]}"; do
	if [[ "${LINUX_IMAGES_VERSIONS[$i]}" == *" $version "* ]]; then
	    echo ${LINUX_IMAGES[$i]}
	fi
    done
}

trunc_llvm_name() {
    version=$1
    echo $version | sed 's/\.//g'
}

## version-specific anchor function
anchor_shared() {
    version=$1
    version_append=$(trunc_llvm_name $version)
    echo ".llvm:$version: &llvm$version_append"
}

anchor_linux() {
    version=$1
    version_image=$(find_image_name $version)
    anchor_shared $version
    echo "  image: $version_image"
    echo "  variables:"
    echo "    LLVM_VERSION: \"$version\""
    echo ""
}

anchor_macos() {
    version=$1
    anchor_shared $version
    echo "  before_script:"
    echo "    - export PATH=\"/usr/local/opt/llvm@${version%%.*}/bin:/usr/local/opt/gnu-getopt/bin:"'$PATH''"'
    echo ""
}

LINUX_ANCHOR_FUN=anchor_linux
MACOS_ANCHOR_FUN=anchor_macos

## pipeline stages (shared between OSes) -- we assume the first stage is a build stage
IFS=', ' read -r -a STAGES <<< "build ftest rtest test"

LINUX_CONFIG_CMD='./configure --with-llvm=`llvm-config-${LLVM_VERSION} --prefix` || (cat config.log; false)'
MACOS_CONFIG_CMD='./configure --with-llvm=`llvm-config --prefix` || (cat config.log; false)'

build_stage() {
    cmd=$1_CONFIG_CMD
    echo ".build:llvm_job: &build"
    echo "  stage: build"
    echo "  script:"
    echo "    - autoreconf --install"
    echo "    - ${!cmd}"
    echo "    - make"
    echo ""
}

ftest_stage() {
    echo ".test:llvm_job: &ftest"
    echo "  stage: ftest"
    echo "  script:"
    echo "    - make ftest"
    echo ""
}

rtest_stage() {
    echo ".test:llvm_job: &rtest"
    echo "  stage: rtest"
    echo "  script:"
    echo "    - make rtest"
    echo ""
}

test_stage() {
    echo ".test:llvm_job: &test"
    echo "  stage: test"
    echo "  only:"
    echo "    - schedules "
    echo "  script:"
    echo "    - make test"
    echo ""
}

for os in LINUX MACOS; do
    {
	# print header
	echo "### DEFAULT PARAMETERS"
	header=${os}_HEADER
	echo "${!header}"

	# print supported versions
	echo "### SUPPORTED VERSIONS"
	versions=${os}_LLVM_VERSIONS
	anchor_fun=${os}_ANCHOR_FUN
	for version in ${!versions}; do
	    ${!anchor_fun} $version
	done

	# print build stages
	echo "### PIPELINE STAGES"
	echo "stages:"
	for stage in ${STAGES[@]}; do
	    echo "  - $stage"
	done
	echo ""

	# print stage templates
	echo "### JOB TEMPLATES"
	for stage in ${STAGES[@]}; do
	    stage_anchor=${stage}_stage
	    $stage_anchor $os
	done

	# print all versions for each stage
	for stage_i in ${!STAGES[@]}; do
	    stage=${STAGES[$stage_i]}
	    echo "### ${stage^^}"
	    for version in ${!versions}; do
		version_append=$(trunc_llvm_name $version)
		echo "$stage:llvm-$version:"
		if [[ $stage_i -gt 0 ]]; then
		    echo "  needs: [\"${STAGES[0]}:llvm-$version\"]"
		fi
		echo "  <<: *llvm$version_append"
		echo "  <<: *$stage"
		echo ""
	    done
	done
    }> "${OUT_PREFIX}${os,,}${OUT_SUFFIX}"
done
