default:
  tags:
    - macosx

.llvm:6.0: &llvm60
  before_script:
    - export PATH="/usr/local/opt/llvm@6/bin:/usr/local/opt/gnu-getopt/bin:$PATH"

.llvm:7: &llvm7
  before_script:
    - export PATH="/usr/local/opt/llvm@7/bin:/usr/local/opt/gnu-getopt/bin:$PATH"

.llvm:8: &llvm8
  before_script:
    - export PATH="/usr/local/opt/llvm@8/bin:/usr/local/opt/gnu-getopt/bin:$PATH"

.llvm:9: &llvm9
  before_script:
    - export PATH="/usr/local/opt/llvm@9/bin:/usr/local/opt/gnu-getopt/bin:$PATH"

stages:
  - build
  - ftest
  - rtest
  - test

.build:llvm_job: &build
  stage: build
  script:
    - autoreconf --install
    - ./configure --with-llvm=`llvm-config --prefix` AR=llvm-ar || (cat config.log; false)
    - make
  artifacts:
    expire_in: 1 week
    paths:
      - ./

.test:llvm_job: &ftest
  stage: ftest
  script:
    - make ftest
  artifacts:
    expire_in: 1 week
    paths:
      - ./

.test:llvm_job: &rtest
  stage: rtest
  script:
    - make rtest
  artifacts:
    expire_in: 1 week
    paths:
      - ./

.test:llvm_job: &test
  stage: test
  only:
    - schedules
  script:
    - make test
  artifacts:
    expire_in: 1 week
    paths:
      - ./

build:llvm-6.0:
  <<: *llvm60
  <<: *build

build:llvm-7:
  <<: *llvm7
  <<: *build

build:llvm-8:
  <<: *llvm8
  <<: *build

build:llvm-9:
  <<: *llvm9
  <<: *build

ftest:llvm-6.0:
  needs: ["build:llvm-6.0"]
  <<: *llvm60
  <<: *ftest

ftest:llvm-7:
  needs: ["build:llvm-7"]
  <<: *llvm7
  <<: *ftest

ftest:llvm-8:
  needs: ["build:llvm-8"]
  <<: *llvm8
  <<: *ftest

ftest:llvm-9:
  needs: ["build:llvm-9"]
  <<: *llvm9
  <<: *ftest

rtest:llvm-6.0:
  needs: ["build:llvm-6.0"]
  <<: *llvm60
  <<: *rtest

rtest:llvm-7:
  needs: ["build:llvm-7"]
  <<: *llvm7
  <<: *rtest

rtest:llvm-8:
  needs: ["build:llvm-8"]
  <<: *llvm8
  <<: *rtest

rtest:llvm-9:
  needs: ["build:llvm-9"]
  <<: *llvm9
  <<: *rtest

test:llvm-6.0:
  needs: ["build:llvm-6.0"]
  <<: *llvm60
  <<: *test

test:llvm-7:
  needs: ["build:llvm-7"]
  <<: *llvm7
  <<: *test

test:llvm-8:
  needs: ["build:llvm-8"]
  <<: *llvm8
  <<: *test

test:llvm-9:
  needs: ["build:llvm-9"]
  <<: *llvm9
  <<: *test
